# Changes here will be overwritten by Copier
_commit: v3.3.2
_src_path: gh:eccenca/cmem-plugin-template
author_mail: streitmatter@informatik.uni-leipzig.de
author_name: Denis Streitmatter
project_description: Load and publish datasets from a DBpedia databus service.
project_slug: databus

