# Changes here will be overwritten by Copier
_commit: v6.0.1
_src_path: gh:eccenca/cmem-plugin-template
author_mail: streitmatter@informatik.uni-leipzig.de
author_name: Denis Streitmatter
github_page: https://github.com/dbpedia/cmem-plugin-databus
project_description: Load and publish datasets from a DBpedia databus service.
project_slug: databus
pypi: true

