# Changes here will be overwritten by Copier
_commit: v4.0.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: streitmatter@informatik.uni-leipzig.de
author_name: Denis Streitmatter
github_page: ''
project_description: Load and publish datasets from a DBpedia databus service.
project_slug: databus
pypi: false

