---
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        exclude: '^tests/.*$'
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: forbidden-files
        name: forbidden files
        entry: found copier update rejection files; review them and remove them
        language: fail
        files: "\\.rej$"

